### ISSUE TITLE
Request for admin rights

### ISSUE THREAD

**Issue by markuskr97** [ob-vss-ss18/ppl-leasing#2]
Can't push to the repository. Please give me admin rights if you can do that. @yhavlik

**Comment by yhavlik** [comment]
Ist gemacht, mir fehlten die github accounts.

**Comment by DomixD** [comment]
@yhavlik bitte den anderen auch noch Admin Rechte geben.

**Comment by yhavlik** [comment]
@DomixD Kennst du die github handles? Ansonsten sollen bitte alle einmal kommentieren.

**Comment by DomixD** [comment]
@yhavlik hab die anderen hinzugefügt.
