### ISSUE TITLE
Modelieren des Datenbankschemas

### ISSUE THREAD

**Issue by DomixD** [ob-vss-ss18/ppl-leasing#20]
Es muss noch eine Postgres Datenbank angebunden werden.

**Comment by markuskr97** [comment]
Gutes Beispiel mit Erklärung:
http://alexandrutopliceanu.ro/post/graphql-with-go-and-postgresql/

**Comment by markuskr97** [comment]
Bitte Postgres Datenbank basierend auf unserer Datenstruktur erstellen

**Comment by Bertlinger** [comment]
DatenStruktur wie folgt:
1. Leasing{
  Kunden_ID
  Leasing_ID(int: referenz auf leasing_id in leased_products)
  Rabatt (int)
  Serviceflat(bool)
  Datum(date)
  peak_flatrate(bool)
  Testwert(int)
  Versicherung(bool) 
}
2. Leased_Products{
Product_ID(int: referenz auf product_id in products(products liegt wo anders))
Leasing_ID(int: referenz auf leasing_id in leasing)

**Comment by markuskr97** [comment]
Fertiggestellt.
