### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-leasing#22]
* Branch `release`
* Pre-Release 1 auf diesen commiten und mit `pre-release-1` taggen
* Auf Heroku deployen
* Heroku `dev` Serive einrichten

Siehe [Release Management](https://github.com/ob-vss-ss18/ppl-core/wiki/Release-Management)

**Comment by ThoGro** [comment]
- [x] Branch `release` erstellt
- [x] Stand des Pre-Release 1 auf diesen committet und mit `pre-release-1` getaggt
- [ ] auf Heroku deployen
- [ ] Heroku `dev` Service einrichten
