### ISSUE TITLE
Planung DB-Schema

### ISSUE THREAD

**Issue by M0CC0** [ob-vss-ss18/ppl-leasing#27]
Bei der Planung des DB-Schemas sind wir auf diverse Logikfehler gestoßen welche darin begründet sind, dass wir nicht exakt abgrenzen können welche Rolle wir im gesamten System einnehmen. Nach unserem aktuellen Verständnis würden wir viele Informationen redundant speichern - existiert eine Dokumentation bzgl. der Rollenverteilung?

**Comment by obcode** [comment]
Wir reden heute in der Vorlesung mal über das Projekt. Ich hoffe da klärt sich das dann.
